apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: customer-demo-service
spec:
  destination:
    name: customer-demo-service
  route:
  - labels:
      version: v1
    weight: 50
  - labels:
      version: v2
    weight: 50
  httpFault:
    delay:
      percent: 10
      fixedDelay: 3s
    abort:
      percent: 10
      httpStatus: 500