
apiVersion: networking.istio.io/v1alpha3

kind: VirtualService

metadata:

  name: customer-demo-service

spec:

  hosts:

    - customer-demo-service

  http:

  - route:

    - destination:

        host: customer-demo-service

        subset: v1

      weight: 50

    - destination:

        host: customer-demo-service

        subset: v2

      weight: 50